// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactPage() {
    driver.get("http://localhost/Foods_store/contact.php");
    driver.manage().window().setSize(new Dimension(790, 824));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Dakshina Dodampoththa ");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("dakshina@gmail.com");
    driver.findElement(By.name("number")).click();
    driver.findElement(By.name("number")).sendKeys("0741245789");
    driver.findElement(By.name("msg")).click();
    driver.findElement(By.name("msg")).sendKeys("fantastic");
    driver.findElement(By.name("send")).click();
  }
}
